### ISSUE TITLE
Better implementation of navbar

### ISSUE THREAD

**Issue by bkzl** [bkzl/hocus-pocus#47]
- [ ] Responsive
- [ ] Better support for background image
- [ ] Possibility to set height
- [ ] Remove navbar-link
- [ ] Sticky navbar

Background image snippet:

```scss
$navbar-height: 75px;

.navbar {
  background-image: url('bg-navbar.png'), url('bg-navbar-left.png'), url('bg-navbar-right.png');
  background-position: top center, top left, top right;
  background-repeat: no-repeat;
  background-size: auto, 50% $navbar-height, 50% $navbar-height;
}
```
